"""Public package surface for lib_registry.

Exposes the Registry class, exception hierarchy, key utilities, and
winreg access constants for pythonic Windows registry access.
"""

from __future__ import annotations

from .__init__conf__ import print_info
from .registry import (
    KEY_ALL_ACCESS,
    KEY_CREATE_LINK,
    KEY_CREATE_SUB_KEY,
    KEY_ENUMERATE_SUB_KEYS,
    KEY_EXECUTE,
    KEY_NOTIFY,
    KEY_QUERY_VALUE,
    KEY_READ,
    KEY_SET_VALUE,
    KEY_WRITE,
    KEY_WOW64_32KEY,
    KEY_WOW64_64KEY,
    RegData,
    Registry,
    RegistryConnectionError,
    RegistryError,
    RegistryHKeyError,
    RegistryHandleInvalidError,
    RegistryKeyCreateError,
    RegistryKeyDeleteError,
    RegistryKeyError,
    RegistryKeyExistsError,
    RegistryKeyNotFoundError,
    RegistryNetworkConnectionError,
    RegistryValueDeleteError,
    RegistryValueError,
    RegistryValueNotFoundError,
    RegistryValueWriteError,
    get_first_part_of_the_key,
    get_hkey_int,
    normalize_separators,
    get_key_as_string,
    get_value_type_as_string,
    hive_names_hashed_by_int,
    is_platform_windows,
    l_hive_names,
    main_key_hashed_by_name,
    reg_type_names_hashed_by_int,
    remove_hive_from_key_str_if_present,
    resolve_key,
    strip_backslashes,
    winreg,
)

__all__ = [
    "print_info",
    # Registry API
    "RegData",
    "Registry",
    "RegistryConnectionError",
    "RegistryError",
    "RegistryHKeyError",
    "RegistryHandleInvalidError",
    "RegistryKeyCreateError",
    "RegistryKeyDeleteError",
    "RegistryKeyError",
    "RegistryKeyExistsError",
    "RegistryKeyNotFoundError",
    "RegistryNetworkConnectionError",
    "RegistryValueDeleteError",
    "RegistryValueError",
    "RegistryValueNotFoundError",
    "RegistryValueWriteError",
    "get_first_part_of_the_key",
    "get_hkey_int",
    "get_key_as_string",
    "normalize_separators",
    "get_value_type_as_string",
    "hive_names_hashed_by_int",
    "is_platform_windows",
    "l_hive_names",
    "main_key_hashed_by_name",
    "reg_type_names_hashed_by_int",
    "remove_hive_from_key_str_if_present",
    "resolve_key",
    "strip_backslashes",
    "winreg",
    # Access constants
    "KEY_ALL_ACCESS",
    "KEY_CREATE_LINK",
    "KEY_CREATE_SUB_KEY",
    "KEY_ENUMERATE_SUB_KEYS",
    "KEY_EXECUTE",
    "KEY_NOTIFY",
    "KEY_QUERY_VALUE",
    "KEY_READ",
    "KEY_SET_VALUE",
    "KEY_WRITE",
    "KEY_WOW64_32KEY",
    "KEY_WOW64_64KEY",
]
